---
title: "Lecture 11. Structural Bioinformatics (Part 1)"
output: github_document
---

## Read CSV file and determine values
```{r}
df <- read.csv("Data Export Summary.csv", row.names = 1)

# Percentage of X-ray determined structures
xray <- df$Total[1]/sum(df$Total)*100
em <- df$Total[2]/sum(df$Total)*100

# All percentages
percent <- df$Total/sum(df$Total)*100
names(percent) <- row.names(df)
percent

# Percentage of proteins
proteins <- sum(df$Proteins)/sum(df$Total)*100

# Print
round(xray, 1)
round(em, 1)
round(proteins, 1)
```

Get data from anywhere using datapasta
```{r}
tmp <- data.frame(stringsAsFactors=FALSE,
   Experimental.Method = c("X-Ray", "NMR", "Electron Microscopy", "Other",
                           "Multi Method", "Total"),
              Proteins = c(124770, 10988, 2057, 250, 127, 138192),
         Nucleic.Acids = c(1993, 1273, 31, 4, 5, 3306),
    ProteinNA.Complex = c(6451, 257, 723, 6, 2, 7439),
                 Other = c(10, 8, 0, 13, 1, 32),
                 Total = c(133224, 12526, 2811, 273, 135, 148969)
)
```


## Bio3D
```{r}
library(bio3d)

```

```{r}
pdb <- read.pdb("1hsg")
```


```{r}
library(bio3d.view)
library(rgl)
view(pdb, "overview", col = "sse")
```

Extract the protein only portion of this PDB structure and wrie it out to a new PDB file.

```{r}
prot <- atom.select(pdb, "protein")
head(pdb$atom[prot$atom, ])
head(pdb$xyz[ ,prot$xyz])

prot.pdb <- trim.pdb(pdb, prot)
write.pdb(prot.pdb, file = "prot.pdb")
```


Extract the ligand (i.e. drug) and write out to a seperate file.
```{r}
lig <- atom.select(pdb, "ligand")
head(pdb$atom[lig$atom, ])
head(pdb$xyz[ ,lig$xyz])

lig.pdb <- trim.pdb(pdb, lig)
write.pdb(lig.pdb, file = "lig.pdb")
```

Access residues
```{r}
pdb$seqres[50:60]
```


