CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Mongolian_gerbil        TKSAKLTCLVTNLASYDTLNISWSSQSGEALETNMKLIESHTNGTFSAEGVAHVCAEDWN
Chinese_hamser          -KSAKLTCLVTNLATYDTLNISWASQSGEPLETNTKLSESHSNGTFSAIGQANVCVADWE
House_mouse             SKSANLTCLVSNLATYETLNISWASQSGEPLETKIKIMESHPNGTFSAKGVASVCVEDWN
Norwegian_rat           TKFAKLSCLVTNLATYDTLNISWSSKSGEPLETNTKIMESHPNGTFSAVGVASVCMEDWD
Human_IGHM              TKSTKLTCLVTDLTTYDSVTISWTRQNGEAVKTHTNISESHPNATFSAVGEASICEDDWN
Rabbit                  SKSARLICLVTDLTTYGSLNISWASHNGKALDTHMNITESHPNATFSAMGEASVCAEDWE
Horse                   TKSAKLSCQVTNLGTYDSLSISWTRQNGEILKTHTNISESHPNGTFSALGEATICVEDWE
Bottlenose_dolphin      TKSAKLSCLVTDLTTYDSLSISRTRQNGEALQTHTNVSESHTNGTFSAVGEASVCVEEWE
Giant_panda             TKSAKLSCLVTDLATYDSLTISWTRQNGEPLKTHTNISESHPNITFSAMGEATVCVEDWE
                         * :.* * *::* :* ::.**.: :.*: :.*: :: ***.* **** * * :*  :*:

Mongolian_gerbil        SRKEFVCTVTHRDLPSPQKKTISKPNEMNR-PPAVYVLPPACEQLILRESVTVTCLVKGF
Chinese_hamser          SGKEFVCTVAHRDLPSPQKKIISKPREVVKQPPAVYLLPPAREQLILREAATVTCLVKGF
House_mouse             NRKEFVCTVTHRDLPSPQKKFISKPNEVHKHPPAVYLLPPAREQLNLRESATVTCLVKGF
Norwegian_rat           NRKEFVCTVTHRDLPSPQKKFISKPNEVAKHPPAVYLLPPAREQLILRESATVTCLVKGF
Human_IGHM              SGERFTCTVTHTDLPSPLKQTISRPKGVALHRPDVYLLPPAREQLNLRESATITCLVTGF
Rabbit                  SGEQFTCTVTHADLPFPLKHTISKSREVAKHPPAVYVLPPAREQLVLRESATVTCLVKGF
Horse                   SGDDYICTVTHTDLPFPLKQAISRPDAVAKHPPSVYVLPPTREQLSLRESASVTCLVKGF
Bottlenose_dolphin      SGERFTCTVTHTDLPSPLKRDISRPTEVAKHMPSVYVLPPTREQLSLRESASVTCLVKGF
Giant_panda             SGEQFTCTVTHTDLPSPLKKTISRPKEVAKHMPSVYVLPPSREQLSLRESASVTCLVKGF
                        . . : ***:* *** * *. **..  :    * **:***: *** ***:.::****.**

Mongolian_gerbil        SPADVLVQWLQRGQPLPSDKYVTSAPMPEPQAQGLYFAYSTLTVAEEEWNSGETYTCVVV
Chinese_hamser          SPADIFVQWLQRGQPLSPDKYVTSAPMPEPQVPGLYFAHSVLTVTEEEWNSGETYTCVVG
House_mouse             SPADISVQWLQRGQLLPQEKYVTSAPMPEPGAPGFYFTHSILTVTEEEWNSGETYTCVVG
Norwegian_rat           SPADIFVQWLQRGQPLSSDKYVTSAPMPEPGAPGLYFTHSILTVTEEEWNSGETYTCVVG
Human_IGHM              SPADVFVQWMQRGQPLSPEKYVTSAPMPEPQAPGRYFAHSILTVSEEEWNTGETYTCVVA
Rabbit                  SPADVFVQWQQRGQPLSSDKYVTSAPAPEPQAPGLYFTHSTLTVTEEDWNSGETFTCVVG
Horse                   SPPDVFVQWLQKGQPLSSDKYVTSAPMPEPQAPGLYFVHSILTVSEEDWSSGETYTCVVG
Bottlenose_dolphin      SPADVFVQWLQKGQPMSSDKYVTSAPAPEPQVPGAYFVYSILTVSEEDWNSGETYTCVVG
Giant_panda             SPPDVFVQWLQKGQPMSPDSYVTSAPTPEPQAPGLYFVHSTLTVSEEDWSAGETYTCVVG
                        **.*: *** *.** :. :.****** *** . * **.:* ***:**:*.:***:**** 

Mongolian_gerbil        HEALPHTVTERTVDQSTGKPTLYNVT-----------
Chinese_hamser          HEALPHMVTERTVDKST--------------------
House_mouse             HEALPHLVTERTVDKSTGK------------------
Norwegian_rat           HEALPHMVTERTVDKSTGKPTLYNVSLIMSDTGGTCY
Human_IGHM              HEALPNRVTERTVDKSTGKPTLYNVSLVMSDTAGTCY
Rabbit                  HEALPHMVTERTVDKSTGKPTLYNVSLIMSDTASTCY
Horse                   HEALPHVVTERTVDKSTGKPTLYNVSLVMSDMASTCY
Bottlenose_dolphin      HEALPHMVTERTVDKSTGKPTLYNVSLVMSDTASTCY
Giant_panda             HEALPHMVTERSVDKSTGKPTLYNVSLVLSDTASTCY
                        *****: ****:**:**                    
